import { Open_Sans } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import Transition from "@/components/Transition";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-openSans",
});

export const metadata = {
  title: "11 Meses",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={openSans.variable}>
        <Header />
        <Transition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
